stages:
  - build

build:
  stage: build
  image: python:3.11
  script:
    - python -m venv venv
    - venv/bin/pip install --upgrade pip
    - venv/bin/pip install -r requirements.txt
  artifacts:
    paths:
      - venv/